# Generated by Django 4.2.1 on 2024-02-06 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_delivery_order_name_order_number_ord_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='number_ord',
        ),
    ]
