# Generated by Django 4.2.1 on 2024-02-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_number_ord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='order',
            name='menu_dish',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ready',
        ),
        migrations.AddField(
            model_name='order',
            name='ready_to_delivery',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
